### ISSUE TITLE
Webpack unexpected token

### ISSUE THREAD

**Issue by matthew-gordon** [Urigo/merge-graphql-schemas#112]
I am using Webpack to compile, running into an issue when trying to call fileLoader on types directory.. 

Webpack config
```
const path = require('path')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  context: __dirname,
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  entry: path.resolve(__dirname + '/src/index.js'),
  output: {
    filename: 'server.js',
    path: path.resolve(__dirname + '/dist')
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: {
          emitError: true
        }
      },
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: [
            ['env']
          ]
        }
      }
    ]
  },
  externals: [nodeExternals()]
}
```

```
(function (exports, require, module, __filename, __dirname) { export default `
                                                                                                     ^^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /Users/matt/Desktop/workspace/projects/rebuilds/slack/slack_api/node_modules/merge-graphql-schemas/dist/index.cjs.js:3796:22
```
I am calling it like so.. 

```const typeDefs = mergeTypes(fileLoader(path.join(__dirname, '../src/schema/types')));```

and the type def..

```
export default `
  type Query {
    hi: String
  }
`;
```
Any thoughts?

**Comment by cfnelson** [comment]
@matthew-gordon Will need to take a look at this and get back to you. Potentially related to the usage of [require](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js#L60) . 

We also expose an [esm bundle](https://github.com/okgrow/merge-graphql-schemas/blob/master/package.json#L12) though I see from the stack trace that the `cjs` bundle is being consumed.

**Comment by matthew-gordon** [comment]
Awesome! Thanks for the quick response! It does successfully work in another project not using Webpack, just have a script with nodemon running --exec babel-node.

**Comment by RichardLitt** [comment]
@matthew-gordon Holiday season here. This project is maintained mainly be maintainers during work hours - we'll get back to you soon.

**Comment by majelbstoat** [comment]
I have a similar issue where it can't `require` the files that are gathered, leading to a message like `Cannot find module 'app/graphql/resolvers/books.js'`, despite it being there, relative to the webpack `context`. `.graphql` files are loaded correctly which made me also wonder about that same line of [code](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js#L60). Tried a couple of things with `NODE_PATH` and `resolve.modules` which didn't work (as expected).

```
[NODEMON] Error: Cannot find module 'app/graphql/resolvers/books.js'
[NODEMON]     at Function.Module._resolveFilename (module.js:469:15)
[NODEMON]     at Function.Module._load (module.js:417:25)
[NODEMON]     at Module.require (module.js:497:17)
[NODEMON]     at require (internal/module.js:20:19)
[NODEMON]     at /path/to/application/node_modules/merge-graphql-schemas/dist/index.cjs.js:3801:22
```

No rush, given the holiday season ;)

**Comment by majelbstoat** [comment]
Happy new year :) Just so I have expectation on how long to live with the workaround, is there likely to be any progress on this any time soon? (The workaround is, uh, "don't use mergeResolvers()" 😬)

**Comment by cfnelson** [comment]
@majelbstoat It has been on are radar internally, sadly I have been quite busy on other projects and haven't had the chance to investigate this error in detail. 😢 

I still believe the usage of `require()` is the most likely cause if it's not a webpack config issue. 2nd option if `require()` isn't the culprit then our `Rollup.js` config could be the cause.

If your able to provide a minimal repo that replicates your issue that would help a lot for testing/validating any potential fixes. 🔥

**Comment by alex996** [comment]
@cfnelson Any updates on this since then? I'm running into a similar issue where Webpack cannot find resolver files. I'm using SSR, so Babel and Webpack are a must. I'm sure it's a subtle problem with the config, but It'd be valuable if we could have an example integration with Webpack in the repo.

**Comment by notsu** [comment]
@cfnelson I have the same issue as @majelbstoat, so I created a demo that replicates our issue below.
https://github.com/notsu/demo-merge-graphql-issue

run `yarn dev`

Does anyone have a workaround or solutions for this issue?

**Comment by cfnelson** [comment]
@notsu Thanks for making a repo of this, it's greatly appreciated! 💯 🙌  We will take a look at it when we get the opportunity and hopefully we can identify the cause. cc @RodMachado

**Comment by aoighost** [comment]
I'm getting similar issues as well tied to deepmerge being referenced

**Comment by maweiyi** [comment]
Has this problem been solved? I have also encountered it.

**Comment by mrdulin** [comment]
same issue. It seems `webpack` does not compile and build my `resolvers.ts` files.

When run the app by `node ./dist/index.js`, `fileloader` try to read my `resolvers.ts` files.

**Comment by cfnelson** [comment]
For anyone interested or having problems with not finding the correct files you need to make sure that your dist/build/bundle e.g your output dir contains your typedefs and resolvers. Take a look at this thread for more context #148 .

The `Unexpected token import` is occurring due to attempting to parse `.js` files in an environment that doesn't support es modules import/export syntax e.g node is expecting `cjs`. This is likely due to your babel/webpack setup and mixing require cjs with imports esm syntax.

Solution is wherever these errors are being reported you can fix this by switching from `export default` to `module.exports =` syntax. As well as switching to using `require` instead of `imports`.

**Comment by viweei** [comment]
I'm also meeting this error today ~ I think the reason for this error in the `fileLoader` method. because when webpack building can't run the method, webpack just only copy this code to target.

befor:
```javascript
import { fileLoader, mergeTypes, mergeResolvers } from 'merge-graphql-schemas';

const df = fileLoader('./typedefs/**/*.gql', { recursive: true });
export const typedefs = mergeTypes(df, { all: true });

const rf = fileLoader('./resolvers/**/*.js');
export const resolvers = mergeResolvers(rf, {
    extensions: ['.js']
});
```

after:
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.resolvers = exports.typedefs = void 0;

var _mergeGraphqlSchemas = require("merge-graphql-schemas");

const df = (0, _mergeGraphqlSchemas.fileLoader)('./typedefs/**/*.gql', {
  recursive: true
});
const typedefs = (0, _mergeGraphqlSchemas.mergeTypes)(df, {
  all: true
});
exports.typedefs = typedefs;
const rf = (0, _mergeGraphqlSchemas.fileLoader)('./resolvers/**/*.js');
const resolvers = (0, _mergeGraphqlSchemas.mergeResolvers)(rf, {
  extensions: ['.js']
});
exports.resolvers = resolvers;
```

so ~ if use webpack packet code. need explicit import GraphQL define. such as:

``` javascript 
# demo.gql
type Query{
    testString: String
}

# demo.js
import Demo from './demo.gql'
```

**Comment by ardatan** [comment]
Same with #98 for the first question.

@viweei But in your case, `fileLoader` is trying to load `graphql` files under `output` files. So you need to copy `graphql` files into `output` files using a copy plugin or something like that.
