### ISSUE TITLE
Support Flowtype

### ISSUE THREAD

**Issue by mxstbr** [Urigo/merge-graphql-schemas#115]
We have `.js` files with Flow types in them like so:

```JS
// resolvers/queries/user/is-pro.js
// ...
import type { User } from 'shared/types';
```

Unfortunately, `fileLoader` chokes on the Flow syntax. :cry:

**Comment by cfnelson** [comment]
@mxstbr Thanks for reporting this, we would be happy to add support for the FileLoader to support parsing Flow as `.ts` is supported. I haven't personally used Flow types yet so I may have the wrong idea (overcomplicated solution).

A potential solution could be to use the [flow-remove-types](https://github.com/flowtype/flow-remove-types) pkg to parse our `.js` files to remove the flow syntax. Unless you are wishing to maintain your Flow type annotations? If  yes maybe we could do a conditional check to use the `flow-parser` if installed? 

Specifically the `const file = require(f);` [line](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js#L60) in `file_loader.js` will likely need to be changed for Flow to be supported.

**Comment by pleerock** [comment]
+1 for typescript support (I think this issue should be renamed to "Support flowtype and typescript typings")

**Comment by cfnelson** [comment]
@pleerock Typescript is already supported. Are you having issues with typescript?

**Comment by pleerock** [comment]
there are no typings, its impossible to typesafely use this library with typescript.

**Comment by damianthekreeeytor** [comment]
+1 for FlowType support

**Comment by Urigo** [comment]
The library has been rewritten in Typescript now.
Any ideas about an easy way to support Flow?
How can we make it happen?

**Comment by Urigo** [comment]
closing as we've got no response.
If you still face an issue feel free to open a new issue
