### ISSUE TITLE
Ability to return GraphQLInputObjectType or GraphQLObjectType for types

### ISSUE THREAD

**Issue by moltar** [Urigo/merge-graphql-schemas#126]
It appears to be not possible, or I am simply missing something. But I am unable to return objects for query types. This is useful for custom types, especially for validation.

E.g.:

```js
const { GraphQLObjectType, GraphQLInt } = require('graphql')
const { GraphQLEmail } = require('graphql-custom-types')

module.exports = new GraphQLObjectType({
  name: 'UserType',
  description: 'Currently logged in user type definition.',
  fields: () => ({
    id: {
      type: GraphQLInt
    },
    email: {
      type: GraphQLEmail
    }
  })
})
```

**Comment by Urigo** [comment]
I don't see any reason why that wouldn't work in the new version.

Can you create a simple reproduction if that is not the case?

Thank you
