### ISSUE TITLE
Resolved correctly first build, returns TypeError: Cannot convert undefined or null to object on each successive

### ISSUE THREAD

**Issue by aeblin** [Urigo/merge-graphql-schemas#133]
Not sure what's happened on my end, but after importing my typeDefs manually, the merge worked correctly and has failed with the above TypeError each successive build attempt. I'm sitting around coding on too little sleep and not enough caffeine, so it wouldn't surprise me if I'm doing something stupid here, but I've run this through a linter, and haven't changed anything since the first successful build. 

Any help would be very much appreciated.

**Comment by cfnelson** [comment]
@aeblin Sadly, I haven't come across this issue before. To be able to better assist you we will need some more info or a minimal working example.

-  Are you using webpack and babel? What plugins etc. 
- could you provide us with an example of your typedefs?
- Can you also provide the stack trace.

To be clear it's your `typeDefs` that are throwing the error when you try to merge them?

**Comment by wildstyles** [comment]
Got the same issue then tried to import empty file. Then imported not blank file - problem dissapeared.

**Comment by RodMachado** [comment]
Hey @aeblin,

Where you able to figure out what was going on?

Cheers

**Comment by ardatan** [comment]
Closed due to inactivity. Feel free to open a new issue if the problem persists.

**Comment by ardatan** [comment]
Available in v1.6.0!
