### ISSUE TITLE
Can you support the dependency of the next types

### ISSUE THREAD

**Issue by advsets** [Urigo/merge-graphql-schemas#143]
For example, the next types, I need to operate user with a table, so that I can introduce the types of user in front.
```
# import User from "../users/user.types.graphql"

type Post {
  author: User,
  createdAt: String,
  id: ID!,
  title: String!,
  slug: String!,
  updatedAt: String
}

type Query {
  allPosts: [Post]
  post(slug: String!): Post
}

type Mutation {
  createPost(title: String!, slug: String!): Post
  updatePost(
    author: User,
    title: String,
    slug: String,
    updatedAt: String
  ): Post
  deletePost(slug: String!): Post
}
```

**Comment by RichardLitt** [comment]
Thanks, @iunfire. Have you tried implementing this with tests? Since this seems like a binary problem (either you can or you can't), I think that you might be able to implement a positive and a negative test yourself. I'd be interested to hear the result.

**Comment by cfnelson** [comment]
@iunfire I am making a wild guess that you might be talking about [next.js](https://github.com/zeit/next.js) TypeScript type definitions? If thats correct could you explain in a little more detail/context as I haven't used it before? And unsure if your attempting to just typecheck or actually import the User type directly which would defeat the purpose of this pkg.

**Comment by iunfire** [comment]
@RichardLitt , @cfnelson  First of all, I'm sorry that I haven't received any reply recently.
I found that , it's, next.js error. not you package question, @cfnelson  think you.

**Comment by kamilkisiela** [comment]
Since it's related to next.js, I'm closing it. Please let me know if it's still relevant.
