### ISSUE TITLE
Possible to not export fileloader on non-node env?

### ISSUE THREAD

**Issue by ipchikin** [Urigo/merge-graphql-schemas#145]
The library breaks on react native now.

**Comment by RichardLitt** [comment]
Thanks, @ipchikin. Did you find a resolution for this?

**Comment by ipchikin** [comment]
@RichardLitt Not sure how to deal with fs on react native. Since this library only builds a index.cjs.js, when metro bundler loads the library, it will load the fs and produce error. Would it be possible so that the fileloader to be separated to another js file or only require node related module in node env?

I am using babel-plugin-import-graphql for client side graphql modularization at the moment. The #import "*.graphql" and extend type works for me.

**Comment by RichardLitt** [comment]
Hmm, good question. I'm not entirely sure. Let's reopen this, in case others run into the same problem, and to let the other maintainers know that this is an open question.

**Comment by ardatan** [comment]
Available in v1.6.0!
