### ISSUE TITLE
Internal error used on expo react-native app

### ISSUE THREAD

**Issue by softglance** [Urigo/merge-graphql-schemas#151]
I tried to use this library in Expo - for react-native application this is causing internal error and not able to compile code saying it is non-node environment.

**Comment by softglance** [comment]
I think, mainly because fs library in not available on non-node environment and so causing the issue. I added fs in my node_modules but still it is failing to compile. Not really sure what should be the fix.

**Comment by RichardLitt** [comment]
Interesting. This sounds like an issue with fs or Expo, as opposed to merge-graphql-schemas. Have you checked their respective repositories for details on this bug?

**Comment by ardatan** [comment]
Available in v1.6.0!

**Comment by zingerj** [comment]
Hi @ardatan, what is the correct way to get this to work in react-native? Not really sure how to define "externals" since it doesn't use Webpack... @softglance were you able to get this to work?

**Comment by ardatan** [comment]
Do you have the problem with the following canary version?
`1.7.7-2266100.0 `

**Comment by zingerj** [comment]
Not sure as I went back to just using `graphql-tag` for now. Will update this thread if I try `merge-graphql-schemas` again in my react-native app.

**Comment by ardatan** [comment]
This package is deprecated so you can use `@graphql-tools/merge` instead. It will solve your issue;
https://www.graphql-tools.com/docs/migration-from-merge-graphql-schemas
