### ISSUE TITLE
Arrays for glob patterns

### ISSUE THREAD

**Issue by konsumer** [Urigo/merge-graphql-schemas#177]
Using [globs](https://www.npmjs.com/package/globs) instead of `glob` for `fileLoader` would allow for arrays as well as the current string-only format. I can make the PR, if this is something people want. It would mean that you can do this:

```js
const typeDefs = mergeTypes(fileLoader([
  `${__dirname}/generated/**/*.graphql`,
  `${__dirname}/server/**/*.graphql`
]), { all: true })
```

**Comment by ardatan** [comment]
Available in v1.6.0!
