### ISSUE TITLE
Question: do directives on objects get merged?

### ISSUE THREAD

**Issue by lastmjs** [Urigo/merge-graphql-schemas#182]
I have a few schemas I'm merging together, and it doesn't seem to be merging in the following directive: `directive @addId on OBJECT`. Just wondering if it is known that object directives are not merged, or if I should do some more digging. Thanks!

**Comment by cfnelson** [comment]
@lastmjs Directives were introduced in this PR https://github.com/okgrow/merge-graphql-schemas/pull/144 and there is a known problem with them -> https://github.com/okgrow/merge-graphql-schemas/issues/156 which I believe should be a simple fix. 

Not sure if this relates to your issue sorry. Would be curious to hear about anything you find!

**Comment by Fi1osof** [comment]
@lastmjs maybe fixed in #183

**Comment by cfnelson** [comment]
@lastmjs I believe the latest fix by `Fi1osof` may do this for you, you should test out [v1.5.8](https://github.com/okgrow/merge-graphql-schemas/releases/tag/v1.5.8) . Let us know if it works for you!!! If not you could create a PR to fix/support this.

**Comment by kamilkisiela** [comment]
Should be [fixed](https://github.com/Urigo/merge-graphql-schemas/pull/196/files#diff-ee59d0638e75272d8511d2bc3e6ae758R859) by #196

**Comment by kamilkisiela** [comment]
It's available now under `v1.6.0-beta.2`. Let us know if it works :)

**Comment by essaji** [comment]
@kamilkisiela after upgrading to `^1.6.0-beta.2` I am not getting the following error:

```
/node_modules/graphql-toolkit/dist/commonjs/epoxy/typedefs-mergers/directives.js:70
        throw new Error(`Unable to merge GraphQL directive "${node.name.value}". \nExisting directive:  \n\t${printedExistingNode} \nReceived directive: \n\t${printedNode}`);
        ^
Error: Unable to merge GraphQL directive "authorized". 
Existing directive:  
        directive @authorized(requires: [Roles] = [ADMIN]) on OBJECT | FIELD_DEFINITION 
Received directive: 
        directive @authorized(requires: String) on OBJECT | FIELD_DEFINITION

```

**Comment by kamilkisiela** [comment]
Yes because you can't merge them because they both have different arguments. Previously (before beta), `merge-graphql-schema` kept those two definitions which is invalid.
