### ISSUE TITLE
Error: Cannot find module 'graphql/utilities/buildASTSchema'

### ISSUE THREAD

**Issue by tomoat** [Urigo/merge-graphql-schemas#186]
node_modules version:1.5.8
node version: 9.11.2

**Comment by tomoat** [comment]
I found this module loaded here

> grep -r 'graphql/utilities/buildASTSchema' ./node_modules

./node_modules/merge-graphql-schemas/dist/index.cjs.js:var buildASTSchema = require('graphql/utilities/buildASTSchema');
./node_modules/merge-graphql-schemas/dist/index.esm.js:import { getDescription } from 'graphql/utilities/buildASTSchema';

**Comment by ack210** [comment]
At the risk of stating the obvious, graphql is a peer dependency.  This is what fixed it for me:

`npm install --save-dev graphql`
