### ISSUE TITLE
Multiples schemas files

### ISSUE THREAD

**Issue by estrada9166** [Urigo/merge-graphql-schemas#187]
I try to merge these 2 schemas and while trying to query it, it was not possible
schema 1
```gql
type User {
  id: ID!
  email: String!
  username: String!
  fullName: String!
  family: FamilyInfo!
}

type Query {
  getMe: User
}
```

schema 2
```gql
type FamilyInfo {
  id: ID!
  father: User!
  mother: User!
  brothers: [User]!
  isLocal: Boolean!
}

extend type Query {
  getFamilyInfoById(id: ID!): FamilyInfo
}
```

I was doing a query with `getFamilyInfoById` and there was an error `Error: Cannot query field "getFamilyInfoById" on type "Query".`

**Comment by vimutti77** [comment]
remove `extend` from schema 2

**Comment by ardatan** [comment]
It supposed to be working in `1.6.0-beta.2`.
