### ISSUE TITLE
Given a single type field with two definitions, how to keep arguments defined in one definition and directive defined in the other

### ISSUE THREAD

**Issue by Renaud009** [Urigo/merge-graphql-schemas#190]
Given that context https://github.com/prisma/prisma/issues/1228#issuecomment-371925718 as suggested by @lastmjs where I'm trying to merge prisma datamodel schema and prisma generated schema from this model while keeping custom directives.

I need to keep custom directives and advanded field arguments (generated by prisma) while avoiding boilerplating. By boilerplating, I mean I know I could take the generated prisma schema.graphql and add to it manually my custom directives but I would need to redo it everytime the model changes.

**datamodel.graphql**
```graphql
type Dataset {
  id: ID! @unique # prisma @unique directive, will be removed in generated SDL but we don't care since its resolved internally by prisma
  name: String! @upper # custom directive that we want in our final SDL
  distributions: [Distribution!]! @filterByAccess(resourceTypeName: "Dataset" actionName: "Read") # custom directive that we want in our final SDL
}
type Distribution {
  id: ID! @unique
}
```

**schema.graphql** generated by prisma based on datamodel.graphql
```graphql
# Prisma removes any unknown custom directives at this point both on objects and fields
# This is the main reason I need to post-merge multiple schemas together
type Dataset implements Node {
  id:  ID!
  name: String!
distributions(where: DistributionWhereInput, orderBy: DistributionOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Distribution!]
}
type Distribution implements Node {
  id: ID!
}
type Query {
  dataset(where: DatasetWhereUniqueInput!): Dataset
  datasets(where: DatasetWhereInput, orderBy: DatasetOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Dataset]!
  distribution(where: DistributionWhereUniqueInput!): Distribution
  distributions(where: DistributionWhereInput, orderBy: DistributionOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Distribution]!
  # Connections too
}
```

**custom.graphql** that expose some new fields unrelated to prisma and define custom authNZ directives that we will want to resolve before or after prisma resolvers and minimizing boilerplating
```graphql
type User {
  name: String!
}
type Query {
  # We defines custom authnz directives at field level
  datasets(where: DatasetWhereInput, orderBy: DatasetOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Dataset]! @filterByAccess(resourceTypeName: "Dataset" actionName: "Read")
  # Naively ignoring prisma parameters will be even less boilerplating too
  distributions: [Distribution]! @filterByAccess(resourceTypeName: "Distribution" actionName: "Read")
}
```

**custom-directives.graphl** which contains all our custom directives
```graphql
directive @filterByAccess(
  resourceTypeName: String = "Dataset"
  actionName: String = "Read"
)  on FIELD | FIELD_DEFINITION
```

Then we try to merge those 4 files into a final SDL **final.graphql**
```javascript
const { importSchema } = require('graphql-import')
const path = require('path')
const {readFileSync, writeFile} = require('fs')
const { mergeTypes } = require('merge-graphql-schemas')

const modelTypeDefs = readFileSync('./github-issue-merge/datamodel.graphql').toString()
const prismaTypeDefs = readFileSync('./github-issue-merge/schema.graphql').toString()
const customTypeDefs = readFileSync('./github-issue-merge/custom.graphql').toString()
const customDirectivesTypeDefs = readFileSync('./github-issue-merge/custom-directives.graphql').toString()

const mergedSchema = mergeTypes([
  modelTypeDefs,
  prismaTypeDefs, // client state schema
  customTypeDefs,
  customDirectivesTypeDefs,
], { all: true })

writeFile(path.join(__dirname, './final.graphql'), mergedSchema.toString(), function(err) {
  if (err) {
    return console.log(err);
  }
  console.log('Schema saved successfully to: ./github-issue-merge/final.graphql');
});
```

**final.graphql** is the merged output of the 3 schemas where we lost the prisma parameters at field level but we managed to keep custom directives
```graphql
schema {
  query: Query
}

type Query {
  dataset(where: DatasetWhereUniqueInput!): Dataset
  datasets(where: DatasetWhereInput, orderBy: DatasetOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Dataset]! @filterByAccess(resourceTypeName: "Dataset", actionName: "Read")
  distribution(where: DistributionWhereUniqueInput!): Distribution
  distributions(where: DistributionWhereInput, orderBy: DistributionOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Distribution]! @filterByAccess(resourceTypeName: "Distribution", actionName: "Read")
  # We defines custom authnz directives at field level
  # Naively ignoring prisma parameters will be less boiler plating too
}

type Dataset {
  id: ID! @unique
  name: String! @upper
  distributions: [Distribution!]! @filterByAccess(resourceTypeName: "Dataset", actionName: "Read")
  # **** We need those parameters at field level too but we lost them!! ****  
}

type Distribution {
  id: ID! @unique
}

type User {
  name: String!
}

directive @filterByAccess(resourceTypeName: String = "Dataset", actionName: String = "Read") on FIELD | FIELD_DEFINITION
```

What I need is the Dataset.distributions 
 -  distributions: [Distribution!]! @filterByAccess(resourceTypeName: "Dataset" actionName: "Read")
 -  distributions(where: DistributionWhereInput, orderBy: DistributionOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Distribution!]

to be merged like this (keeping advanded arguments and directives)
-   distributions(where: DistributionWhereInput, orderBy: DistributionOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Distribution]! @filterByAccess(resourceTypeName: "Distribution", actionName: "Read")

Is there a wat to archieve this with arguments perhaps on mergeTypes? Any help is welcome.

Thanks

**Comment by lastmjs** [comment]
I believe I just ran into the exact same issue. I really need those parameters to remain in the merged schema

**Comment by lastmjs** [comment]
I found a workaround in my own project, doing some custom AST manipulations. I'll probably do a pull request here and try to get argument merging officially supported. Also, I'll be updating https://medium.com/@lastmjs/advanced-graphql-directive-permissions-with-prisma-fdee6f846044 soon, hopefully with some npm packages to make this all much easier to deal with. Full directive permissions for all CRUD operations should be possible, it's working quite well within my own project

**Comment by Urigo** [comment]
@lastmjs @Renaud009 can you please try again with the new latest version?

If that won't work, can you create a reproduction or maybe even a failing test?

Thanks

**Comment by Urigo** [comment]
closing as got no response
