### ISSUE TITLE
Make package size smaller

### ISSUE THREAD

**Issue by tbaustin** [Urigo/merge-graphql-schemas#197]
![Screen Shot 2019-06-19 at 8 16 07 AM](https://user-images.githubusercontent.com/14001400/59768789-8e1d8a00-926a-11e9-85a2-e099935121e0.png)

I think it should be easier to make these smaller right?

**Comment by Urigo** [comment]
Might be related this [this](https://github.com/ardatan/graphql-toolkit/issues/175)

**Comment by ardatan** [comment]
It is around `131.68KB` including `graphql` (which is common in all graphql packages); we also seperated  graphql-toolkit's functions into smaller packages. So it is better right now.
