### ISSUE TITLE
Get error with "apollo-server-express": "^2.6.6"

### ISSUE THREAD

**Issue by thearabbit** [Urigo/merge-graphql-schemas#199]
I got error when update to `"apollo-server-express": "^2.6.5"`

```js
TypeError: Cannot read property 'some' of undefined
```

**Comment by Urigo** [comment]
can you try seeing if that still is the case with the new beta?

https://github.com/Urigo/merge-graphql-schemas/pull/196

**Comment by thearabbit** [comment]
thanks for your reply.
I will follow this
