### ISSUE TITLE
how to make it work with webpack?

### ISSUE THREAD

**Issue by sibelius** [Urigo/merge-graphql-schemas#202]
how to import many .graphql files?

**Comment by ardatan** [comment]
What are you trying to do? If you'd like to import graphql files in webpack, you can take a look at this;
https://www.apollographql.com/docs/react/recipes/webpack/

**Comment by sibelius** [comment]
file-loader does not work with webpack

we used require.context to import multiple .graphql files

**Comment by ardatan** [comment]
Actually fileLoader isn't something you should use with webpack while webpack has its own module system. FileLoader uses NodeJS's module system. Personally I don't recommend to use webpack on server side. But if you use webpack, fileLoader is not compatible with webpack.

**Comment by Urigo** [comment]
a note about none Node environments here: https://github.com/Urigo/merge-graphql-schemas#note-for-non-node-environments-webpack-and-rollup
