### ISSUE TITLE
Argument of type 'string[]' is not assignable to parameter of type 'ResolversDefinition<unknown>[]

### ISSUE THREAD

**Issue by ksaifullah** [Urigo/merge-graphql-schemas#210]
I have a typescript project where I'm following below instruction from readme:
---
Or automatically:

```js
// ./graphql/resolvers.js
import path from 'path';
import { fileLoader, mergeResolvers } from 'merge-graphql-schemas';

const resolversArray = fileLoader(path.join(__dirname, './resolvers'));

export default mergeResolvers(resolversArray);
```

> Beware that `mergeResolvers` is simply merging plain Javascript objects together.
This means that you should be careful with Queries, Mutations or Subscriptions with naming conflicts.
---

And getting following error where I have `mergeResolvers()`:
> error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'ResolversDefinition<unknown>[]'.
Type 'string' is not assignable to type 'ResolversDefinition<unknown>'.

There is a conflict between what `fileLoader()` returns and what `mergeResolvers()` expects.

Appreciate if someone is able to help.

Note that, all my packages are up to date.

**Comment by ksaifullah** [comment]
Looks like the issue is coming from **graphql-toolkit** project where probably `loadSchemaFiles()` got changes recently.

**Comment by ardatan** [comment]
Could you try the following version to see if works;
`1.6.2-bdaf070.0`

**Comment by epictrave** [comment]
@ardatan I have same issue. I tried `1.6.2-bdaf070.0` but it show same problem.
`error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'ResolversDefinition<unknown>[]'.
  Type 'string' is not assignable to type 'ResolversDefinition<unknown>'.`

**Comment by ksaifullah** [comment]
Yep, same as @epictrave .
I would request to avoid `any` type, if possible.

**Comment by TomBeckett** [comment]
Also hit the same issue. No luck with version 1.6.2-bdaf070.0.

**Comment by ardatan** [comment]
Could you try `1.6.2-3705b28.0` instead?

**Comment by ksaifullah** [comment]
Thanks @ardatan , `1.6.2-3705b28.0` works for me.

**Comment by kamilkisiela** [comment]
Fixed with `v1.7.0`

**Comment by SinghRajKr** [comment]
Getting the same issue.
Argument of type 'string[]' is not assignable to parameter of type 'ResolversDefinition<unknown>[]'.      
  Type 'string' is not assignable to type 'ResolversDefinition<unknown>'

**Comment by VladimirTambovtsev** [comment]
Getting the same with <code>^1.7.6</code>

<code>Argument of type 'string[]' is not assignable to parameter of type 'ResolversDefinition<unknown>[]'.
  Type 'string' is not assignable to type 'ResolversDefinition<unknown>'.ts(2345)
</code>

```node
import { fileLoader, mergeResolvers, mergeTypes } from 'merge-graphql-schemas'
import path from 'path'

const allResolvers: string[] = fileLoader(
  path.join(__dirname, './api/**/*.resolvers.*')
)

const mergedResolvers = mergeResolvers(allResolvers)
```
