### ISSUE TITLE
Option for leaving off `schema`

### ISSUE THREAD

**Issue by konsumer** [Urigo/merge-graphql-schemas#241]
I am trying to use amplify to generate the boring parts of a CRUD interface. I want to merge a bunch of individual query files, but leave off the parent `schema` object so amplify can handle it (it seems to throw it off from making mutations or subscriptions, which breaks `@auth` and other things.)

Here is a code example:

```ts
import GraphQLTransform from 'graphql-transformer-core'
import AppSyncDynamoDBTransformer from 'graphql-dynamodb-transformer'
import AppSyncElasticsearchTransformer from 'graphql-elasticsearch-transformer'
import AppSyncConnectionTransformer from 'graphql-connection-transformer'
import AppSyncAuthTransformer from 'graphql-auth-transformer'
import { fileLoader, mergeTypes } from 'merge-graphql-schemas'

const typeDefs = mergeTypes(fileLoader(`${__dirname}/schema/**/*.graphql`), { all: true }).toString()

const transformer = new GraphQLTransform({
  transformers: [
      new AppSyncDynamoDBTransformer(),
      new AppSyncElasticsearchTransformer(),
      new AppSyncAuthTransformer(),
      new AppSyncConnectionTransformer()
  ]
})
const cfdoc = transformer.transform(typeDefs)
```

typeDefs ends up having this:

```graphql
schema {
  query: Query
}
```
even though there is no `Query` in my graphql files. It works fine if I make a string that looks identical and just leave that off.

Is there interest in a PR for an option to disable the root? What should we call it?

**Comment by konsumer** [comment]
as a hacky workaround, I can do this:

```graphql
typeDefs.toString().replace('schema {\n  query: Query\n}', '')
```

Since I know it doesn't have a `Query`, but it'd be cool if I could just leave off `schema` in merge-graphql-schemas output (and it would allow me to write custom `Query` and `Mutation` fields.)

**Comment by ardatan** [comment]
You can pass `schemaDefinition: false` in the options.
```ts
const typeDefs = mergeTypes(fileLoader(`${__dirname}/schema/**/*.graphql`), { all: true, schemaDefinition:false }).toString()
```

**Comment by konsumer** [comment]
Sorry I missed that, and thanks!
