### ISSUE TITLE
Bad performance when loading resolvers with a glob pattern

### ISSUE THREAD

**Issue by julianomqs** [Urigo/merge-graphql-schemas#283]
Hello,

I'm using `merge-graphql-schema` in my project and I noticed a bad performance when loading resolvers with a glob pattern.

It's a TypeScript project with Apollo Server for GraphQL and Objection.js for persistence.

The glob pattern is `src/**/*-resolver.ts`.

The folder structure is:

```
src
    perfil
        perfil-service.ts
        perfil-resolver.ts
    usuario
        usuario-service.ts
        usuario-resolver.ts
package.json
```

It takes almost 4 seconds to load those resolvers.

The resolvers are just some arrow functions declared as constants and the exported object referencing those functions. They imports some generated classes from GraphQL schema and a stateless service class that does some persistence operations.

**Comment by ardatan** [comment]
@julianomqs I created a sandbox to reproduce your issue to see if there is a significant load time of `fileLoader`. There are 3 resolver and 3 typeDef files in this sandbox. 
https://codesandbox.io/s/holy-hill-merwp?fontsize=14

**Comment by julianomqs** [comment]
Sorry for not making a testcase earlier and troubling you.

Here I made a reproducible example:

https://github.com/julianomqs/merge-graphql-schemas-performance

Run `npm install` and `npm start`

You'll see the fileLoader is taking more than 3 seconds to read 3 resolvers in 3 folders.

Thank you.

**Comment by ardatan** [comment]
I changed `fileLoader` line for resolvers like below;
```
console.time('load resolvers manually');
require('./perfil/perfil-resolver');
require('./scalar/scalar-resolver');
require('./usuario/usuario-resolver');
console.timeEnd('load resolvers manually');
```
It takes more than 3 seconds as well :)

**Comment by julianomqs** [comment]
I found it, it was `ts-node` fault...

Sorry for taking your time, and thanks for your library.
