### ISSUE TITLE
Include path & filename for syntax errors label:enhancement

### ISSUE THREAD

**Issue by peterhanneman** [Urigo/merge-graphql-schemas#307]
Tracking down `GraphQLError: Syntax Error`s within projects with numerous type definition files with nested folder structures is unnecessarily tedious because the filename and path aren't included in the error along with the line number.

**Comment by ardatan** [comment]
@peterhanneman I don't think this problem is related to this library. There is no parser logic in file loaders, it just loads the definitions as string. Also in schema and resolver mergers, it is not possible to know the source of the type definitions.
