### ISSUE TITLE
fileloader is not working. 

### ISSUE THREAD

**Issue by RabieZahid** [Urigo/merge-graphql-schemas#308]
I tried the basic implementation as follows, where I have a some _types_ defined in ._js_/_.graphql_ files within the **types** subdirectory. 

`const typesArray = fileLoader(path.join(__dirname, "./types"))`

I get an empty array in response. If I manually import the files and merge them, it works. It just the fileLoader that fails to load the files. I'm using **"merge-graphql-schemas": "^1.7.4"**

**Comment by RabieZahid** [comment]
It worked with a relative path from app root directory as follows: 

`const typesArray = fileLoader('./src/graphql/types/*.graphql')`

Not sure if something got updated in **graphql-toolkit** but this way worked.

**Comment by xie-zhichao** [comment]
I also got this problem, 1.7.3 is ok.

**Comment by stamtech** [comment]
Hello Guys, same here, seems related to the last release of graph toolkit you are using in your last release.
("@graphql-toolkit/file-loading": "0.6.7" )

Switching back to 1.7.3 works fine

**Comment by ardatan** [comment]
Could you try with `0.7.5`?

**Comment by ardatan** [comment]
Closing this issue. Feel free to open a new one if you still have problems :)
