### ISSUE TITLE
TypeScript Error: Codegen resolvers don't satisfy constraint of mergeResolvers

### ISSUE THREAD

**Issue by ostrebler** [Urigo/merge-graphql-schemas#346]
I generated my resolver typings with [GraphQL Codegen](https://graphql-code-generator.com/docs/plugins/typescript-resolvers) (with optionality set to true : not all fields require explicit resolvers), which basically outputs something like : 

```typescript
export type Resolvers<ContextType> = {
  Foo?: FooResolvers<ContextType>;
  Bar?: BarResolvers<ContextType>;
};
```

The problem is that this doesn't satisfy the constraint imposed by `mergeResolvers`, so this code : 

```typescript
import path from "path";
import { fileLoader, mergeResolvers } from "merge-graphql-schemas";
import { Context, Resolvers } from "./graphql/types";

export default {
  resolvers: mergeResolvers<Context, Resolvers<Context>>(
    fileLoader(path.join(__dirname, "./graphql/*.resolvers.js"))
  )
};

```

produces the following TypeScript error : 
```
Type 'Resolvers<Context>' does not satisfy the constraint 'ResolversDefinition<Context>'.
  Type 'Resolvers<Context>' is not assignable to type 'IResolvers<any, Context>'.
    Property 'Foo' is incompatible with index signature.
      Type 'FooResolvers<Context, FooDb> | undefined' is not assignable to type '(() => any) | GraphQLScalarType | IEnumResolver | IResolverObject<any, Context, any> | IResolverOptions<any, Context, any>'.
        Type 'undefined' is not assignable to type '(() => any) | GraphQLScalarType | IEnumResolver | IResolverObject<any, Context, any> | IResolverOptions<any, Context, any>'.
```

I think you might want to add `undefined` as a possible type for a resolver. Thank you in advance.

Of course applying [Required](https://www.typescriptlang.org/docs/handbook/utility-types.html#requiredt) is not enough since it's shallow : the same error just pops up from deeper in the resolver tree. Current workaround :

```typescript
export default {
  resolvers: mergeResolvers<Context, any>(
    fileLoader(path.join(__dirname, "./graphql/*.resolvers.js"))
  ) as Resolvers<Context>
};

```

**Comment by ardatan** [comment]
Could you enable this flag on the codegen and try again?
https://graphql-code-generator.com/docs/plugins/typescript-resolvers#useindexsignature-boolean-default-value-false

**Comment by ostrebler** [comment]
It works but why ?

**Comment by ardatan** [comment]
IResolvers of graphql-tools needs a index signature that doesn't exist in generated resolver typings of codegen by default.
