### ISSUE TITLE
Unknown type "Query"

### ISSUE THREAD

**Issue by eladnm** [Urigo/merge-graphql-schemas#380]
I am getting the following error when trying to debug my project
```
Error: Unknown type "Query".
    at assertValidSDL (/Users/eladnahum/node_modules/graphql/validation/validate.js:89:11)

```
I am not sure how to resolve this issue? can someone please point me what should I look and add?
Thanks

**Comment by ardatan** [comment]
Could you share a reproduction repo?

**Comment by eladnm** [comment]
> Could you share a reproduction repo?

Sorry I could only share part of the code.. What could be the cause of this error? The api works great but when using the vs code and node debugger

**Comment by ardatan** [comment]
I am not sure. I need to reproduce it to see the reason.

**Comment by eladnm** [comment]
> I am not sure. I need to reproduce it to see the reason.

please let me know what files to share as i cannot share all code

**Comment by ardatan** [comment]
I cannot tell much but as I see in the stack trace it is not related to merge-graphql-schemas but graphql tools.

**Comment by FranOnRails** [comment]
I have the same error, I used {all: true} and there was an error in a graphql tools function, I also think it is it.

**Comment by ardatan** [comment]
@FranOnRails could you reproduce it in a repo?

**Comment by eladnm** [comment]
> I have the same error, I used {all: true} and there was an error in a graphql tools function, I also think it is it.
to what file are you referring? where is this function located?

**Comment by ardatan** [comment]
````
at Object.makeExecutableSchema (/Users//node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29) <<--- This is the function coming from graphql-tools
at Object. (/Users//apollo.config.ts:20:26)  <<-- This is where you called it
```
So that looks like an issue in graphql-tools.
