### ISSUE TITLE
Proposal: Ability to add auth resolvers

### ISSUE THREAD

**Issue by dan-kez** [Urigo/merge-graphql-schemas#70]
Hello!

First, thank you for making this extremely useful module. It has really helped me keep my code modular. 

I've recently been working on adding authorization to my graphql schema (where some queries/ mutation have different read/write permissions). I think it would be really useful to be able to add in the ability to merge an auth resolver mapping. This would really help modularize authorization.

Quick pseudo code example:
```
// resolvers.js
export default {
    Query: {
        async cocktails() {  return await db.cocktails.all();  },
    },

    Mutation: {
        async createCocktail(root, {newCocktail }) { return await db.cocktail.save(newCocktail); },
    }
}
```

```
// authResolvers.js
import { GraphQLError } from 'graphql';
import { isTokenSessionValid, hasWritePermissions } from '../utils/auth';

const checkReadPermission = (token) => {
    if ( !isTokenSessionValid(token) ) {
        throw new GraphQLError({ message: "You don't have read permissions" })
    }
};

const checkWritePermission = (token) => {
    if ( ! (isTokenSessionValid(token) && hasWritePermissions(token)) ) {
        throw new GraphQLError({ message: "You don't have write permissions" })
    }
};

export default {
    authQuery: {
        cocktails(root, args, { token }) {  return checkReadPermission(token) },
    },

    authMutation: {
         cocktails(root, args, { token }) {  return checkWritePermission(token); },
    }
}
```

```
// rootResolvers.js
import { mergeResolvers } from 'merge-graphql-schemas';
import resolvers from './resolvers';
import authResolvers from './authResolvers';

export default mergeResolvers([
   resolvers,
   authResolvers,
]);
```

**Comment by RodMachado** [comment]
Hey @dmk255,

Sorry for not responding earlier!

So, if I understood correctly, you would like to create new additional operations (like Query, Mutation and Subscription)? Does this work on a plain GraphQL setup? 
Changing the package to parse this information might not be that hard (#FamousLastWords), I'm just not sure if we should. 

If you're using Apollo, take a look in the approach using the apollo-resolvers package. I personally think it looks good.
https://github.com/thebigredgeek/apollo-resolvers
https://www.youtube.com/watch?v=xaorvBjCE7A&feature=youtu.be

Cheers!

**Comment by dchambers** [comment]
@RodMachado, while people may choose to take the approach used by [apollo-resolvers](https://github.com/thebigredgeek/apollo-resolvers) it seems wrong to prevent the idiomatic way of doing authentication in GraphQL. Couldn't `mergeTypes` take an optional (defaulted) second parameter containing the `mergeableBaseTypes`?

**Comment by ardatan** [comment]
You can use this in order to compose resolvers;
https://github.com/ardatan/graphql-toolkit#composeresolvers
